-- CreateTable
CREATE TABLE "Bearing" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "company" TEXT NOT NULL,
    "Type" TEXT NOT NULL,
    "d" DOUBLE PRECISION NOT NULL,
    "D" DOUBLE PRECISION NOT NULL,
    "T" DOUBLE PRECISION NOT NULL,
    "d1" DOUBLE PRECISION NOT NULL,
    "B" DOUBLE PRECISION NOT NULL,
    "C_m" DOUBLE PRECISION NOT NULL,
    "r1" DOUBLE PRECISION NOT NULL,
    "r2" DOUBLE PRECISION NOT NULL,
    "r3" DOUBLE PRECISION NOT NULL,
    "r4" DOUBLE PRECISION NOT NULL,
    "a" DOUBLE PRECISION NOT NULL,
    "C_k" DOUBLE PRECISION NOT NULL,
    "C_o" DOUBLE PRECISION NOT NULL,
    "e" DOUBLE PRECISION NOT NULL,
    "Y" DOUBLE PRECISION NOT NULL,
    "Y_o" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "Bearing_pkey" PRIMARY KEY ("id")
);
